**Numpy is a commonly used packg used for scientific computing in Python.It provides a multidim. array obj, as well as variation such as marks and matrices, which can be used for various mathematical operations. It is comatible with other pckgs- matplotlib and pandas

In [2]:
import numpy as np
array1=np.array([1,2,3,4,5,6,7,8])
print(array1)
print(type(array1))
print(array1[5])
array1.dtype

[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>
6


dtype('int32')

In [4]:
array2=np.array([[1,2,3,4,5,6]])        # result is 2D matrices format 
print("ORIGINAL MATRIX",array2,'\n')

print(type(array2))                             #1  2  3  4  5  6

array2.dtype

print('\n',"SHAPE OF THE ARRAY IS:- ",array2.shape)

array2[0,2]=9             # row 0 , col 2 has been assigned a new value = 9

print('\n',"PRINT UPDATED MATRIX",'\n',array2)

ORIGINAL MATRIX [[1 2 3 4 5 6]] 

<class 'numpy.ndarray'>

 SHAPE OF THE ARRAY IS:-  (1, 6)

 PRINT UPDATED MATRIX 
 [[1 2 9 4 5 6]]


In [5]:
# Since only 1 [] used so it is just row 1
print(array2[0,0])           # rep in a manner : row , col
print(array2[0,1])
print(array2[0,2])
print(array2[0,3])

1
2
9
4


***DIFFERENT METHODS TO CONSTRUCT A MATRIX

1. PYTHON STRUCTURE - differentiated [] , []
2. np.zeros() - creates a mtrix with elem. as 0
3. np.identity() - creates a matric as identity elem , diagonal elem =1
4. np.empty() - random numbers assigned
5. np.empty_like()
6. np.arange() - displays the result wrt defined value
7. np.linspace(x,y,z) - x= start point ; y= end point ; z= interval in which it is to be divided

In [6]:
# TO CREATE MULTIPLE ROWS use differentiated [] , [] using python structure

array3=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(array3)
print('\n',"SHAPE OF THE ARRAY IS:- ",array3.shape)
print('\n',"ELEMENTS IN THE ARRAY IS:- ",array3.size)
print('\n',"ACCES THE ELEMENT IN ROW 1 AND COL 2:- ",array3[1,2] )
print('\n',array3[0,0],'\n',array3[0,1],'\n',array3[0,2],'\n',array3[1,0],'\n',array3[1,1],'\n',array3[1,2],'\n',array3[2,0],'\n',array3[2,1],'\n',array3[2,2])



[[1 2 3]
 [4 5 6]
 [7 8 9]]

 SHAPE OF THE ARRAY IS:-  (3, 3)

 ELEMENTS IN THE ARRAY IS:-  9

 ACCES THE ELEMENT IN ROW 1 AND COL 2:-  6

 1 
 2 
 3 
 4 
 5 
 6 
 7 
 8 
 9


In [7]:
# creating arrays with intrinsic numpy array obj
# zeros() func - inserts 0 in defined row and col
x=np.zeros((5,6))
print(x,'\n',"SHAPE OF THE GIVEN MATRIX:- ",x.shape,'\n',"SIZE OF THE MATRIX:-",x.size)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] 
 SHAPE OF THE GIVEN MATRIX:-  (5, 6) 
 SIZE OF THE MATRIX:- 30


In [8]:
rg = np.arange((20))     # array gets created as per the defined range
print(rg)
#print(rg[3:6]) - O/P-> values of specified range will be displayed

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [9]:
# np.linspace(x,y,z) - x= start point ; y= end point ; z= interval in which it is to be divided
lspace = np.linspace(11,20,10)     # divide the interval into 10 equal intervals b/t 11 to 20
print(lspace)
print("______________________________________________________________________________",'\n')
lspace1 = np.linspace(1,20,20)     # divide the interval into 20 equal intervals b/t 1 to 20
print(lspace1)
print("______________________________________________________________________________",'\n')
lspace2 = np.linspace(1,40,15)     # divide the interval into 15 equal intervals b/t 1 to 14
print(lspace2)

[11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
______________________________________________________________________________ 

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20.]
______________________________________________________________________________ 

[ 1.          3.78571429  6.57142857  9.35714286 12.14285714 14.92857143
 17.71428571 20.5        23.28571429 26.07142857 28.85714286 31.64285714
 34.42857143 37.21428571 40.        ]


In [10]:
emty=np.empty((4,4))     # O/P: random numbers assigned
print(emty)

[[4.67296746e-307 1.69121096e-306 1.95820760e-306 1.33506605e-306]
 [6.23056330e-307 2.22522597e-306 1.33511969e-306 1.37962320e-306]
 [9.34604358e-307 9.79101082e-307 1.78020576e-306 1.69119873e-306]
 [2.22522868e-306 1.24611809e-306 8.06632139e-308 1.60221208e-306]]


In [11]:
lspace = np.linspace(11,20,15)     # divide the interval into 10 equal intervals b/t 11 to 20
print(lspace)
print("______________________________________________________________________________",'\n')
emty1=np.empty_like(lspace)
print(emty1)

[11.         11.64285714 12.28571429 12.92857143 13.57142857 14.21428571
 14.85714286 15.5        16.14285714 16.78571429 17.42857143 18.07142857
 18.71428571 19.35714286 20.        ]
______________________________________________________________________________ 

[11.         11.64285714 12.28571429 12.92857143 13.57142857 14.21428571
 14.85714286 15.5        16.14285714 16.78571429 17.42857143 18.07142857
 18.71428571 19.35714286 20.        ]


In [12]:
# IDENTITY MATRIX : np.identity() 
idt=np.identity(5)
idt

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
range1=np.arange((20))
print(range1)
print('\n',"SHAPE OF THE MATRIX IS:- ",range1.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

 SHAPE OF THE MATRIX IS:-  (20,)


In [14]:
range1.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [15]:
# ravel() - opposite of reshape. It changes the 2D array having row, col to 1D array.
range1= range1.ravel()
print(range1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [16]:
rg2=np.arange(100)
print(rg2,'\n\n\n',rg2.reshape(10,10),'\n\n\n',rg2.reshape(5,20),'\n\n\n',rg2.reshape(20,5))
print('\n',"SHAPE OF THE MATRIX IS:-",rg2.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99] 


 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]] 


 [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]] 


 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]

**NUMPY AXIS ROW OPERATION - axis=0 (operates down the column) COLUMN OPERATION - axis=1 (operates along the column)

In [17]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('ORIGINAL MATRIX IS:-','\n',x,'\n')
print("ROW OPERATION",'\n',x.sum(axis=0),'\n')
print("COLUMN OPEARTION",'\n',x.sum(axis=1))

ORIGINAL MATRIX IS:- 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

ROW OPERATION 
 [12 15 18] 

COLUMN OPEARTION 
 [ 6 15 24]


In [18]:
y=np.array([[20,22,24],[26,28,30],[31,33,35]])
print(y,'\n')
print("ROW OPERATION",'\n',y.sum(axis=0),'\n')
print("COLUMN OPEARTION",'\n',y.sum(axis=1))

[[20 22 24]
 [26 28 30]
 [31 33 35]] 

ROW OPERATION 
 [77 83 89] 

COLUMN OPEARTION 
 [66 84 99]


In [19]:
z=np.arange(20,35)
print(z,'\n')
m=z.reshape(3,5)
print(m,'\n')


[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34] 

[[20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]] 



In [20]:
print("ROW OPERATION",'\n',m.sum(axis=0),'\n')
print("COLUMN OPEARTION",'\n',m.sum(axis=1))

ROW OPERATION 
 [75 78 81 84 87] 

COLUMN OPEARTION 
 [110 135 160]


In [21]:
# TRASPOSE OF ARRAY 
print(x)
print('\n',"SHAPE OF THE ORIGINAL MATRIX IS:-",x.shape,'\n\n')
d=x.T
print(d,'\n\n',"SHAPE OF THE TRANSPOSE MATRIX IS:-",d.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 SHAPE OF THE ORIGINAL MATRIX IS:- (3, 3) 


[[1 4 7]
 [2 5 8]
 [3 6 9]] 

 SHAPE OF THE TRANSPOSE MATRIX IS:- (3, 3)


In [22]:
# DIMENSION - .ndim - this gives us the dimension of the matrix
x.ndim

2

In [23]:
x.nbytes

36

In [24]:
x.argmax()        # returns the index of the highest value

8

In [25]:
x.argmin()        # returns the index of the minimum value

0

In [26]:
y=np.array([[20,22,24],[26,28,30],[31,33,35]])
print(y,'\n')
print(y.argmax())
print(y.argmin())

[[20 22 24]
 [26 28 30]
 [31 33 35]] 

8
0


In [27]:
# SORTING
y=np.array([1,2,4,5,8,99,1,1,2,22,55,78])
print(y,'\n')


[ 1  2  4  5  8 99  1  1  2 22 55 78] 



MATRIX ADDITION , SUBT ,MULTIPL, DIVIS ETC. (MATRIX OPERATIONS)

In [29]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
a=np.array([[11,12,13],[14,15,16],[17,18,19]])
print("MATRIX ADDITION",x+a,'\n\n')
print("MATRIX SUBTARCTION",x-a,'\n\n')
print("MATRIX MULTIPLICATION",x*a,'\n\n')
print('\n\n',"_____________________________",'\n\n')
print("SQUARE ROOT OF a:-  ",np.sqrt(a),'\n')
print("SUM OF a:-  ",a.sum(),'\n')
print("___________________________________",'\n')
print(a,'\n',"MIN VALUE OF a:-  ",a.min(),'\n')

MATRIX ADDITION [[12 14 16]
 [18 20 22]
 [24 26 28]] 


MATRIX SUBTARCTION [[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]] 


MATRIX MULTIPLICATION [[ 11  24  39]
 [ 56  75  96]
 [119 144 171]] 




 _____________________________ 


SQUARE ROOT OF a:-   [[3.31662479 3.46410162 3.60555128]
 [3.74165739 3.87298335 4.        ]
 [4.12310563 4.24264069 4.35889894]] 

SUM OF a:-   135 

___________________________________ 

[[11 12 13]
 [14 15 16]
 [17 18 19]] 
 MIN VALUE OF a:-   11 



In [30]:
a.mean()

15.0

In [31]:
a.mean(axis=0)

array([14., 15., 16.])

In [32]:
a.mean(axis=1)

array([12., 15., 18.])

In [33]:
a.sum()

135

In [34]:
a.sum(axis=0)

array([42, 45, 48])

In [35]:
a.sum(axis=1)

array([36, 45, 54])

In [36]:
b=np.array([4,5,6,7,8,10])
np.where(b>9)       # returns the index where b>9

(array([5], dtype=int64),)